version: '2.1'
services:
  db_load:
    image: mysql:5.7.29
    command: sh -c "for f in $$(ls /data/); do mysqlimport -h db_serv -u root -ptgacbrowser tgac_browser_demo --local /data/$$f; done;"
    depends_on:
      db_serv:
        condition: service_healthy
    volumes:
      - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./mysql-data:/data
    environment:
      MYSQL_ROOT_PASSWORD: tgacbrowser
      MYSQL_USER: tgacbrowser
      MYSQL_PASSWORD: tgacbrowser
    ports:
      - "3309:3306"

  db_serv:
    image: mysql:5.7.29
    ports:
      - "3308:3306"
    expose:
      - "3308"
    volumes:
      - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./mysql-dump/tgac_browser_demo.sql:/docker-entrypoint-initdb.d/tgac_browser_demo.sql
    environment:
      MYSQL_ROOT_PASSWORD: tgacbrowser
      MYSQL_DATABASE: tgac_browser_demo
      MYSQL_USER: tgacbrowser
      MYSQL_PASSWORD: tgacbrowser
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  blast_db:
    image: mysql:5.7.29
    ports:
      - "3310:3306"
    expose:
      - "3310"
    volumes:
      - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./mysql-dump/tgac_browser_demo_blast_manager.sql:/docker-entrypoint-initdb.d/tgac_browser_demo_blast_manager.sql
    environment:
      MYSQL_ROOT_PASSWORD: tgacbrowser
      MYSQL_DATABASE: tgac_browser_demo_blast_manager
      MYSQL_USER: tgacbrowser
      MYSQL_PASSWORD: tgacbrowser
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  tb:
    build: .
    ports:
      - "8888:8080"
    volumes:
      - ./annotations:/home/user/datafiles
      - ./webapps:/usr/local/tomcat/webapps
      - ./scripts:/usr/local/bin/scripts
      - ./blast-files:/tmp
    depends_on:
      db_serv:
        condition: service_healthy
